### ISSUE TITLE
Missing property maven.jar.plugin.version

### ISSUE THREAD

**Issue by dktsni** [Decathlon/parent#3]
Hi @lusoalex !

I try to integrate ARA with this parent pom, but was unable to do it due to the declaration of the property `maven.jar.plugin.version` in the plugin maven-jar-plugin. 

But this property was never defined in this pom (unlike the compiler which have a defined property version).

Is that possible to add the value of this property ?

Thx !

**Comment by lusoalex** [comment]
I'm working on this

**Comment by lusoalex** [comment]
Hi @dktsni, I pushed a new snapshot 1.1-SNAPSHOT on maven central.
Could you do a test with this one?
https://oss.sonatype.org/#nexus-search;quick~com.decathlon
Regards,
Alexandre.

**Comment by dktsni** [comment]
Hi @lusoalex !

Yep, I've just tried it on the https://github.com/Decathlon/ara/issues/87 and it works now :) 

Thanks !

**Comment by lusoalex** [comment]
> Hi @lusoalex !
> 
> Yep, I've just tried it on the [Decathlon/ara#87](https://github.com/Decathlon/ara/issues/87) and it works now :)
> 
> Thanks !

Thanks for your feedback. I will generate a new release now and keep you up to date.

**Comment by lusoalex** [comment]
The 1.1 has been released and published on maven: https://search.maven.org/artifact/com.decathlon/parent/1.1/pom
